# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.svg"

[footer]
since = 2024
customText = """<img src="/img/beian.png" style="width: 11px;">&nbsp;<a href="https://beian.mps.gov.cn/#/query/webSearch?code=43010302002115" rel="noreferrer" target="_blank">æ¹˜å…¬ç½‘å®‰å¤‡43010302002115å·</a>&nbsp;&nbsp;<a href="https://beian.miit.gov.cn/" target="_blank">æ¹˜ICPå¤‡2024097599å·</a>&nbsp;"""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸš€"
emojiLight = "ğŸŒ¾"
emojiDark = "ğŸšœ"
subtitle = "æœæ— ç•Œï¼Œè§éå‡¡"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = "zh-CN"
visitor = ""
avatar = ""
emoji = [""]
requiredMeta = ["nick", "email", "url"]
placeholder = "æ¬¢è¿æå‡ºä»»ä½•é—®é¢˜æˆ–å»ºè®®ï¼"

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "aisearchkit/feedback"
repoID = "R_kgDOOFfn_w"
category = "Q&A"
categoryID = "DIC_kwDOOFfn_84CnuuW"
mapping = "title"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
